# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3

    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v4
      # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
      with:
        comment-summary-in-pr: always
      #   fail-on-severity: moderate
      #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
      #   retry-on-snapshot-warnings: true      
